# Generated by Django 4.1.3 on 2022-11-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RELACION', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='cirugias',
            field=models.CharField(blank=True, default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='decendencia',
            field=models.CharField(blank=True, default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='enfermedades',
            field=models.CharField(blank=True, default='No', max_length=2, null=True),
        ),
    ]
